---
  description: |
    Note\: yaml format prohibits using tabulations.

    Optional parameters, if not provided, are automatically set to the default value provided with the given program.

  author: "Claire Rioualen & Jacques van Helden"
  qsub: "-V -m a -d ."  # qsub options, which should be adapted to the local configuration
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"
    size: "4639221"
    fasta_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.dna.genome.fa"
    gff3_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gff3"
    gtf_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gtf"
#    fasta_url: "ftp://ftp.ensemblgenomes.org/pub/release-21/bacteria/fasta/bacteria_22_collection/escherichia_coli_str_k_12_substr_mg1655/dna/Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.dna.genome.fa.gz"            # required for genome download: provide url to .fa.gz
#    gff3_url: "ftp://ftp.ensemblgenomes.org/pub/release-21/bacteria/gff3/bacteria_22_collection/escherichia_coli_str_k_12_substr_mg1655/Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gff3.gz"                          # required for annotation_download: provide url to .gff3.gz
#    gtf_url: "ftp://ftp.ensemblgenomes.org/pub/release-21/bacteria/gtf/bacteria_22_collection/escherichia_coli_str_k_12_substr_mg1655/Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gtf.gz"

  metadata:
    samples: "gene-regulation/examples/RNA-seq_PE_GSE41190/samples.tab"                                    # required. has to contain at least sample ids
    design: "gene-regulation/examples/RNA-seq_PE_GSE41190/design.tab"                                      # required. has to contain at least ids of pairs of samples to be compared
    configfile: "gene-regulation/examples/RNA-seq_PE_GSE41190/config.yml"                        # required for flowcharts generation; maybe this should be revised
    seq_type: "pe"
    strands: "1 2"

  dir:
    reads_source: "data"                                                       # opt
    fastq: "fastq"                                                                 # required
    genome: "genome"                                                          # required. where to store genomes
    results: "results"                                                         # required. dir for all result files that are produced by the pipeline
    gene_regulation: "gene-regulation"                                         # required. location of the snakemake library

    samples: "results/samples"                                # optional. will hold sample treatment (trimming, alignment, QC...).    If not mentioned, will be config["dir"]["results"]
    diffexpr: "results/diffexpr"                                       # optional. will hold the results of differential expression analysis.  If not mentioned, will be config["dir"]["results"]
    reports: "results/reports"                                # optional. will hold reports and graphics.                             If not mentioned, will be config["dir"]["results"]

  tools:                                                        # required
    trimming: "sickle"
    mapping: "bowtie2"
    read_counts: "featureCounts"
    diffexpr: "edgeR DESeq2"
    infer_transcripts: "cufflinks"

  fastqc: 
    other_options: ""

  sickle:
    threshold: "20"                                                             # ... 

  bowtie2:
    max_mismatches: "1"
    threads: "10"

  subread-align:
    threads: "10"
    seq_data: "0"                       ## Sequence type for subread-align. 0=RNA-seq, 1=genomic DNA-seq
    max_mismatches: "3" 
    align_options: "-d 0 -D 600"        ## Additional options for subread-align

  subread-featureCounts:
    attr_type: "gene_id" 
    feature_type: "exon"
    strand_specificity: 1               ## strand-specific read counting.  0 (unstranded), 1 (stranded) and 2 (reversely stranded). 
    multi_mapping: ""

  bowtie:
    max_mismatches: "1"
    threads: "10"

  bwa:
    threads: "10"

  tophat:
    max_mismatches: "1"
    threads: "10"

  cufflinks:
    threads: "4"
    libtype: "fr-firststrand"

  edgeR:
    featuresToRemove: "NULL"
    varInt: "group"
    condRef: "WT"
    batch: NULL
    alpha: "0.05"
    pAdjustMethod: "BH"
    cpmCutoff: "1"
    gene_selection: "pairwise"
    normalizationMethod: "TMM"

  DESeq2:
    featuresToRemove: NULL                          # c("alignment_not_unique", "ambiguous", "no_feature", "not_aligned", "too_low_aQual")
    varInt: "group"
    condRef: "WT"
    batch: "NULL"
    fitType: "parametric"                           # "parametric" (default) or "local"
    cooksCutoff: "TRUE"
    independentFiltering: "TRUE"
    alpha: "0.05"
    pAdjustMethod: "BH"                             # "BH" (default) or "BY"
    typeTrans: "VST"                                # "VST" or "rlog"
    locfunc: "median"                               # "median" (default) or "shorth" to estimate the size factors

  blastall:
    organism: "Arabidopsis_thaliana"
    db_fasta: "genome/TAIR10/TAIR10.fa"
    db: "genome/TAIR10/TAIR10_blastdb_pT"
    matrix: "BLOSUM62"

